const ActionTypes = {
  CLEAR_LYRICS: 'CLEAR_LYRICS',
  LYRIC_GENERATION_FAILURE: 'LYRIC_GENERATION_FAILURE',
  LYRIC_GENERATION_REQUEST: 'LYRIC_GENERATION_REQUEST',
  LYRIC_GENERATION_SUCCESS: 'LYRIC_GENERATION_SUCCESS'
}

export default ActionTypes
